// Service worker of the web version (iPad / browser).
//
// Goal: the app OPENS without network (recipes themselves are stored in the
// browser database). Strategy "network first, cache as fallback":
//  * online  -> always the latest deployed version (and the cache is refreshed);
//  * offline -> the last version seen.
// Only the app files (same origin) and Google font/CanvasKit files are
// cached. Supabase requests are NEVER intercepted.

// Replaced by tool/build_web.ps1 at each build: a new version makes the
// browser install this worker again and download the new app files.
const BUILD_VERSION = '20261002-214316';
const CACHE = 'recettes-app';
const NETWORK_TIMEOUT_MS = 4000;
const CACHEABLE_HOSTS = ['fonts.gstatic.com', 'fonts.googleapis.com', 'www.gstatic.com'];

// Minimal shell if precache.json is missing (e.g. `flutter run`).
const SHELL = ['./', 'index.html', 'flutter_bootstrap.js', 'flutter.js', 'main.dart.js'];

// precache.json (generated by tool/build_web.ps1) lists every file the app
// needs, including the CanvasKit variant of each browser and the fallback
// font: without them the app would not start offline.
async function filesToPrecache() {
  try {
    const response = await fetch('precache.json', { cache: 'no-store' });
    if (response.ok) return ['./', ...(await response.json())];
  } catch (_) { /* offline or missing: minimal shell */ }
  return SHELL;
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const files = await filesToPrecache();
    await Promise.allSettled(
      files.map((url) => cache.add(new Request(url, { cache: 'no-store' }))),
    );
    console.info(`Recettes ${BUILD_VERSION}: ${files.length} files cached for offline use`);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key !== CACHE) await caches.delete(key); // older naming schemes
    }
    await self.clients.claim();
  })());
});

function isCacheable(request) {
  if (request.method !== 'GET') return false;
  const url = new URL(request.url);
  if (url.origin === self.location.origin) return true;
  return CACHEABLE_HOSTS.includes(url.hostname);
}

function withTimeout(promise, ms) {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error('timeout')), ms);
    promise.then((value) => { clearTimeout(timer); resolve(value); },
                 (error) => { clearTimeout(timer); reject(error); });
  });
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (!isCacheable(request)) return; // e.g. Supabase: straight to network

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    try {
      const response = await withTimeout(fetch(request), NETWORK_TIMEOUT_MS);
      if (response && (response.ok || response.type === 'opaque')) {
        cache.put(request, response.clone());
      }
      return response;
    } catch (error) {
      const cached = await cache.match(request, { ignoreSearch: true });
      if (cached) return cached;
      if (request.mode === 'navigate') {
        const shell = await cache.match('index.html');
        if (shell) return shell;
      }
      throw error;
    }
  })());
});
